pipeline { 
agent any 
    stages { 
        stage ('Build') { 
            steps { 
          sh 'mvn clean install'

                def pom = readMavenPom file:'pom.xml'
            }
        }

    }           
 }
