pipeline { 
agent any 
    stages { 
        stage ('Build') { 
            steps { 
                echo " clean package"
            }
        }
        stage ('Test') {
            steps {
                 //sh "mvn test "
                echo "this is testing"
            }
          
        }  
            
        

    }           
 }
