pipeline { 
agent any 
    stages { 
        stage ('Build') { 
            steps { 
                echo " clean package"
            }
        }
        stage ('Test') {
            steps {
                 sh "mvn test /var/lib/jenkins/workspace/pipeline1/HelloWorldProject/pom.xml"
            }
          
        }  
            
        

    }           
 }
